volumes:
  grafana_data: {}

networks:
  front-tier:
  back-tier:
services:
  db:
    image: postgres:latest
    # container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: monitoring
    networks:
      - back-tier
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    networks:
      - back-tier
      - front-tier
    ports:
      - "8080:8080"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"
    restart: always
    depends_on:
      - db
    networks:
      - back-tier
      - front-tier
    ports:
      - "3000:3000"
    volumes:
      - .config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    # environment:
    #   GF_SECURITY_ADMIN_PASSWORD: admin
    #   GF_AUTH_ANONYMOUS_ENABLED: "true"
    #   GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    #   GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."